### ISSUE TITLE
Convert the source to RST

### ISSUE THREAD

**Issue by bfabio** [teamdigitale/dati-semantic-guida-ndc-docs#16]
I'm not sure Docs Italia will support Markdown, [the guide (Italian)](https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/scrivere-un-documento.html) mentions only RST.

We should convert the Markdown files to RST, just to be sure.

cc @AgostinoPurificato

**Comment by AgostinoPurificato** [comment]
cc @Clou-dia

**Comment by Clou-dia** [comment]
this issue can be closed I guess

**Comment by bfabio** [comment]
Ye, the guide is RST-based now.
