### ISSUE TITLE
Add the copyright owner

### ISSUE THREAD

**Issue by bfabio** [teamdigitale/dati-semantic-guida-ndc-docs#17]
The repo's [README.md](../blob/main/README.md) only states the licence (CC-BY-4.0), but it doesn't say about the copyright owner. The [AUTHORS](../blob/main/AUTHORS) file is also empty

**Comment by Clou-dia** [comment]
[Updated Authors ](https://github.com/teamdigitale/dati-semantic-guida-ndc-docs/pull/29)

**Comment by bfabio** [comment]
Thanks @Clou-dia, closing.
